### ISSUE TITLE
MongoDB cannot login, always Authentication failed

### ISSUE THREAD

**Issue by ardinusawan** [cognitom/momy#11]
MongoDB username and password are correct. I am using mlab.com.
If src in momyfile.json is my localhost, this code run without problem.
But, if src is another ip address (in this case i use mlab.com), I got message error 

> (node:4177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Authentication failed.

Maybe in this code auth using MONGODB-CR, not SCRAM-SHA-1?

Regards

**Comment by cognitom** [comment]
Hi @ardinusawan, `momy` just calls `MongoClient. connect()` method.
https://github.com/cognitom/momy/blob/v0.7.0/lib/tailer.js#L178

See also this document:
http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#.connect

It seems that the library only supports `GSSAPI` or `MONGODB-CR` at this point.
https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/url_parser.js#L307

**Comment by cognitom** [comment]
@ardinusawan I've found the test for `scram`. It should work.
https://github.com/mongodb/node-mongodb-native/blob/V2.2.21/test/functional/scram_tests.js#L30

**Comment by ardinusawan** [comment]
So the solution is 
mongodb.connect(this.url2?authMechanism=SCRAM-SHA-1&authSource=admin&maxPoolSize=5).then(db => { ......

Right?

**Comment by cognitom** [comment]
Looks close. You can write that in your `momyfile.json`. I haven't tried but It could be like this:

```json
{
  "src": "mongodb://somewhere:27017/dbname?authMechanism=SCRAM-SHA-1"
}
```

**Comment by ardinusawan** [comment]
Still cannot connect :(

**Comment by cognitom** [comment]
@ardinusawan `momy` needs *replica set cluster*. Don't you use database in *Single-node sandbox*?
If you don't have the right to access `oplog`, it would fail.
http://docs.mlab.com/oplog/#connecting-to-the-oplog

**Comment by ardinusawan** [comment]
Yes im using Single-node sandbox.
So, now im move to digitalocean droplet.
I try to run script in droplet, src as localhost.
But when I run 
> momy --config momyfile.json --import

There is another error message ( not error auth message again :D ) 
> (node:4378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'ts' of null

What wrong?

**Comment by cognitom** [comment]
Hmm, it seems that `momy` couldn't get the information of `ts` (timestamp) from MySQL table. Could you check that `mongo_to_mysql` table was automatically created?
https://github.com/cognitom/momy#mysql

If not, your account might not have the privileges to create tables on MySQL.

**Comment by ardinusawan** [comment]
Yeah `mongo_to_mysql` was automatically created :-/

**Comment by ardinusawan** [comment]
Finally it work. Thx
