### ISSUE TITLE
First record empty and data not synced

### ISSUE THREAD

**Issue by seuaCoder** [cognitom/momy#34]
I have a bug when i import the data, the first record is always empty. Then when i lunch the daemon i have this log:

1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
1 Feb 10:02:51 - Replace a record in statistics (_id=undefined)
... 

If i update some data in Mongo, nothing is happening in Mysql.

Where this issue can come from?

**Comment by CitizenDev** [comment]
I have similar issue, did you resolve it?

**Comment by cognitom** [comment]
If you were using MongoDB 5.x, this issue was fixed in momy v0.8.1 related to #35 .
