### ISSUE TITLE
Custom converters or filters

### ISSUE THREAD

**Issue by cognitom** [cognitom/momy#5]
I've started thinking about *custom converters* or *filters* to solve #2 and #3 .
Here's just my brain storming...

### Solution 1

Add these global fields to `momyfile.json`:

- `"exclusions": "\uFFFD"`: if this field is set, these chars will be automatically removed.
- `"inclusions": "\x00-\x7F"`: if this field is set, any other chars will be automatically removed.

Some pros and cons:

- **pros**: simple and enough for the issues at this point
- **cons**: not flexible

### Solution 2

Make `momyfile` scriptable:

- use `momyfile.js` for more complex setting
- `"globalConverter": (val, type, fieldName, colName) => {/** do something **/}`

Some pros and cons:

- **pros**: max flexibility. Users can freely extend it as they like.
- **cons**: too complex

**Comment by cognitom** [comment]
@odedelharar how about *Solution 1* ?
If it fits your case, I think I could implement it, soon.

**Comment by odedelharar** [comment]
Hi,
I think the first solution would be enough for my case.
Thanks!

**Comment by cognitom** [comment]
Ok, done.
momy@0.7.0 has been published.
@odedelharar pls check it out 😉
